include:
  - local: ".gitlab/configuration-central-validation.yml"
  - project: 'DataDog/apm-reliability/apm-sdks-benchmarks'
    file: '.gitlab/ci-rust-axum-realworld-parallel.yml'
    # clone the right branch from the right repo
    ref: 'fayssal/test-rust'

stages:
  - config-validation
  - rust-axum-realworld-parallel
  - rust-axum-realworld-parallel-slo

variables:
  REPO_LANG: rust
  REPO_NOTIFICATION_CHANNEL: "#dd-trace-rs-alerts"

default:
  tags: ["arch:amd64"]

# Config inversion CI steps
validate_supported_configurations_v2_local_file:
  stage: config-validation
  image: registry.ddbuild.io/ci/libdatadog-build/packaging:100425777
  rules:
    - when: on_success
  extends: .validate_supported_configurations_v2_local_file
  variables:
    LOCAL_JSON_PATH: "supported-configurations.json"
    BACKFILLED: "true"

# Executed on release tag datadog-opentelemetry-vx.y.z
update_central_configurations_version_range_v2:
  stage: config-validation
  image: registry.ddbuild.io/ci/libdatadog-build/packaging:100425777
  rules:
    - if: '$CI_COMMIT_TAG =~ /^datadog-opentelemetry-v[0-9]+\.[0-9]+\.[0-9]+$/'
      when: on_success
  extends: .update_central_configurations_version_range_v2
  variables:
    LOCAL_REPO_NAME: "dd-trace-rs"
    LOCAL_JSON_PATH: "supported-configurations.json"
    LANGUAGE_NAME: "rust"
    SEND_ALIASES: "true"
    TAG_PREFIX: "datadog-opentelemetry-v"
