name: "Bug Report (Low Priority)"
description: "Create a public Bug Report. Note that these may not be addressed as quickly as the helpdesk and that looking up account information will be difficult."
title: "[BUG]: "
labels: bug
body:
  - type: input
    attributes:
      label: Tracer Version(s)
      description: "Version(s) of the tracer affected by this bug"
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    attributes:
      label: Rust Version(s)
      description: "Version(s) of Rust (`Rust --version`) that you've encountered this bug with"
      placeholder: "Rust 1.80.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Report
      description: Please add a clear and concise description of the bug here
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Code
      description: Please add code here to help us reproduce the problem
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error Logs
      description: "Please provide any error logs from the tracer (`DD_TRACE_DEBUG=true` can help)"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Libraries in Use
      description: "Which crates and their versions are you using?"
    validations:
      required: false

  - type: input
    attributes:
      label: Operating System
      description: "Provide your operating system and version (e.g. `uname -a`)"
      placeholder: Darwin Kernel Version 23.6.0
    validations:
      required: false
