import json
import subprocess

supported_configurations_file = open("supported-configurations.json", "r")
supported_configurations = json.load(supported_configurations_file)

# PLEASE DO NOT ADD ANYTHING TO THIS LIST.
# Only reason this exists is to test the code with fake env vars.
undocumented_configurations = {
    "DD_COMPLEX_STRUCT": {
        "aliases": [],
        "deprecated": False,
    },
    "DD_NONEXISTANT_CONFIGURATION": {
        "aliases": ["DD_NONEXISTANT_CONFIGURATION_ALIAS", "DD_NONEXISTANT_CONFIGURATION_DEPRECATED_ALIAS"],
        "deprecated": False,
    },
    "DD_NONEXISTANT_CONFIGURATION_ALIAS": {
        "aliases": [],
        "deprecated": False,
    },
    "DD_NONEXISTANT_CONFIGURATION_DEPRECATED": {
        "aliases": [],
        "deprecated": True,
    },
}

enum_block = ""
as_str_block = ""
aliases_block = []
is_alias_deprecated = []
is_deprecated = []
for i, key in enumerate(supported_configurations["supportedConfigurations"].keys()):
    if i != 0:
        enum_block += "\n"
        as_str_block += "\n"
    enum_block += f"    {key},"
    as_str_block += f"            SupportedConfigurations::{key} => \"{key}\","
    aliases_accumulator = []
    deprecated = False
    for version in supported_configurations["supportedConfigurations"][key]:
        if "aliases" in version:
            for alias in version["aliases"]:
                aliases_accumulator.append(alias)
                if alias not in supported_configurations["supportedConfigurations"].keys():
                    is_alias_deprecated.append(alias)
        if "deprecated" in version and version["deprecated"]:
            is_deprecated.append(key)
    if len(aliases_accumulator) > 0:
        aliases_block.append(f"SupportedConfigurations::{key} => &[{', '.join(f'\"{a}\"' for a in aliases_accumulator)}],")
        

if len(undocumented_configurations) > 0:
    enum_block += "\n\n    /// Used for testing purposes only"
for i, key in enumerate(undocumented_configurations):
    enum_block += f"\n    #[allow(unused)]\n    {key},"
    as_str_block += f"\n            SupportedConfigurations::{key} => \"{key}\","
    if len(undocumented_configurations[key]["aliases"]) > 0:
        aliases_block.append(f"SupportedConfigurations::{key} => &[{', '.join(f'\"{a}\"' for a in undocumented_configurations[key]["aliases"])}],")
    if undocumented_configurations[key]["deprecated"]:
        is_deprecated.append(key)
    for alias in undocumented_configurations[key]["aliases"]:
        if alias not in undocumented_configurations.keys():
            is_alias_deprecated.append(alias)

result = f"""\
// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

/// This file is generated by the scripts/local_config_map_generate.py script.
/// Do not edit this file manually. To add a new configuration,
/// add it to the supported-configurations.json file, then run this script.
#[allow(nonstandard_style)]
#[derive(Debug, PartialEq, Copy, Clone)]
#[non_exhaustive]
pub(crate) enum SupportedConfigurations {{
{enum_block}
}}

impl SupportedConfigurations {{
    pub fn as_str(&self) -> &'static str {{
        match self {{
{as_str_block}
        }}
    }}

    pub fn aliases(&self) -> &[&'static str] {{
        match self {{
            {"\n            ".join(aliases_block)}
            _ => &[],
        }}
    }}

    pub fn is_deprecated(&self) -> bool {{
        matches!(self, {" | ".join(f"SupportedConfigurations::{key}" for key in is_deprecated)})
    }}
}}

pub(crate) fn is_alias_deprecated(name: &str) -> bool {{
    matches!(name, {" | ".join(f"\"{alias}\"" for alias in is_alias_deprecated)})
}}
"""

with open("dd-trace/src/configuration/supported_configurations.rs", "w") as f:
    f.write(result)

# run cargo fmt
subprocess.run(["rustfmt", "dd-trace/src/configuration/supported_configurations.rs"])
