import json
import subprocess

supported_configurations_file = open("supported-configurations.json", "r")
supported_configurations = json.load(supported_configurations_file)

# PLEASE DO NOT ADD ANYTHING TO THIS LIST.
# Only reason this exists is to test the code with fake env vars.
undocumented_configurations = {
    "DD_COMPLEX_STRUCT": {
        "aliases": [],
        "deprecated": False,
    },
    "DD_NONEXISTANT_CONFIGURATION": {
        "aliases": ["DD_NONEXISTANT_CONFIGURATION_ALIAS"],
        "deprecated": False,
    }
}

enum_block = ""
as_str_block = ""
aliases_block = ""
deprecated_block = ""
for i, key in enumerate(supported_configurations["supportedConfigurations"].keys()):
    if i != 0:
        enum_block += "\n"
        as_str_block += "\n"
        aliases_block += "\n"
        deprecated_block += "\n"
    enum_block += f"    {key},"
    as_str_block += f"            SupportedConfigurations::{key} => \"{key}\","
    aliases_accumulator = []
    deprecated = False
    for version in supported_configurations["supportedConfigurations"][key]:
        if "aliases" in version:
            for alias in version["aliases"]:
                aliases_accumulator.append(alias)
        if "deprecated" in version and version["deprecated"]:
            deprecated = True
    
    aliases_block += f"            SupportedConfigurations::{key} => &[{', '.join(f'\"{a}\"' for a in aliases_accumulator)}],"
    deprecated_block += f"            SupportedConfigurations::{key} => {str(deprecated).lower()},"

        

if len(undocumented_configurations) > 0:
    enum_block += "\n\n    /// Used for testing purposes only"
for i, key in enumerate(undocumented_configurations):
    enum_block += f"\n    #[allow(unused)]\n    {key},"
    as_str_block += f"\n            SupportedConfigurations::{key} => \"{key}\","
    aliases_block += f"\n            SupportedConfigurations::{key} => &[{', '.join(f'\"{a}\"' for a in undocumented_configurations[key]["aliases"])}],"
    deprecated_block += f"\n            SupportedConfigurations::{key} => {str(undocumented_configurations[key]["deprecated"]).lower()},"

result = f"""\
// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

/// This file is generated by the scripts/local_config_map_generate.py script.
/// Do not edit this file manually. To add a new configuration,
/// add it to the supported-configurations.json file, then run this script.
#[allow(nonstandard_style)]
#[derive(Debug, PartialEq, Copy, Clone)]
#[non_exhaustive]
pub(crate) enum SupportedConfigurations {{
{enum_block}
}}

impl SupportedConfigurations {{
    pub fn as_str(&self) -> &'static str {{
        match self {{
{as_str_block}
        }}
    }}

    pub fn aliases(&self) -> &[&'static str] {{
        match self {{
{aliases_block}
        }}
    }}

    #[allow(dead_code)]
    pub fn is_deprecated(&self) -> bool {{
        match self {{
{deprecated_block}
        }}
    }}
}}
"""

with open("dd-trace/src/configuration/supported_configurations.rs", "w") as f:
    f.write(result)

# run cargo fmt
subprocess.run(["rustfmt", "dd-trace/src/configuration/supported_configurations.rs"])
