import json

supported_configurations_file = open("supported-configurations.json", "r")
supported_configurations = json.load(supported_configurations_file)

enum_block = ""
as_str_block = ""
for i, key in enumerate(supported_configurations["supportedConfigurations"].keys()):
    if i == 0:
        enum_block += f"    {key}"
        as_str_block += f"            SupportedConfigurations::{key} => \"{key}\""
    else:
        enum_block += f",\n    {key}"
        as_str_block += f",\n            SupportedConfigurations::{key} => \"{key}\""

result = f"""\
// Copyright 2025-Present Datadog, Inc. https://www.datadoghq.com/
// SPDX-License-Identifier: Apache-2.0

/// This file is generated by the scripts/local_config_map_generate.py script.
/// Do not edit this file manually.
/// To add a new configuration, add it to the supported-configurations.json file, then run the script.

#[allow(nonstandard_style)]
#[non_exhaustive]
pub enum SupportedConfigurations {{
{enum_block}
}}

impl SupportedConfigurations {{
    fn as_str(&self) -> &'static str {{
        match self {{
{as_str_block}
        }}
    }}
}}
"""

with open("dd-trace/src/configuration/supported_configurations.rs", "w") as f:
    f.write(result)
