name: Check Pull Request CI Status

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  checks: read
  statuses: read
  actions: read

jobs:
  ensure-ci-success:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ensure CI Success
        uses: DataDog/ensure-ci-success@727e7fe39ae2e1ce7ea336ec85a7369ab0731754 # v2.1.1
        with:
          # Checks for 15mn (30 * 30s)
          max-retries: 30
          polling-interval-seconds: 30
